DOCKER_MANTAINER_NAME=mrakitin
DOCKER_NAME=olog-server
DOCKER_RUN_NAME=olog-server
DOCKER_TAG=latest
DOCKER_NETWORK=olog-network

OLOG_VERSION=2.2.9
OLOG_ADMIN_PORT=4848
OLOG_SSL_PORT=8181
ADMIN_PASSWORD=password
CERTIFICATE_PASSWORD=password
USER_PASSWORD=1234
DB_USER=olog_user
DB_PASSWORD=password
DB_URL=olog-mysql-db
DB_PORT=3306
DB_NAME=olog
